# Generated by Django 5.2.8 on 2025-12-02 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('B', 'Borehole'), ('W', 'Well'), ('T', 'Tap'), ('R', 'River Intake'), ('P', 'Public Pump')], max_length=1)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('status', models.CharField(choices=[('O', 'Operational'), ('M', 'Maintenance Required'), ('B', 'Broken/Non-Operational'), ('C', 'Contaminated')], default='O', max_length=1)),
                ('installation_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField(default=django.utils.timezone.now)),
                ('work_done', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='waterapp.watersource')),
            ],
            options={
                'ordering': ['-repair_date'],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('priority_level', models.IntegerField(default=1)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='waterapp.watersource')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
