# Generated by Django 5.2.8 on 2025-12-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuereport',
            old_name='issue_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='watersource',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has this source been verified for water quality?'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='water_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='waterapp.watersource'),
        ),
        migrations.AlterField(
            model_name='watersource',
            name='name',
            field=models.CharField(help_text='E.g., Nairobi Zone A', max_length=100),
        ),
        migrations.AlterField(
            model_name='watersource',
            name='status',
            field=models.CharField(choices=[('O', 'Operational'), ('M', 'Maintenance'), ('B', 'Broken/Non-Operational'), ('C', 'Contaminated')], default='O', max_length=1),
        ),
    ]
