# Generated by Django 5.2.8 on 2025-12-02 16:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0002_rename_issue_description_issuereport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='repairlog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
