# Generated by Django 5.2.8 on 2025-12-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0004_watersource_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersource',
            name='source_type',
            field=models.CharField(choices=[('BH', 'Borehole'), ('WL', 'Well'), ('TP', 'Tap'), ('RI', 'River Intake'), ('PP', 'Public Pump')], max_length=2),
        ),
        migrations.AlterField(
            model_name='watersource',
            name='status',
            field=models.CharField(choices=[('O', 'Operational'), ('M', 'Maintenance'), ('B', 'Broken/Non-Operational'), ('C', 'Contaminated')], default='O', max_length=2),
        ),
    ]
