# Generated by Django 5.2.8 on 2025-12-19 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0005_alter_watersource_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='Contact number for orders', max_length=15)),
                ('location_name', models.CharField(help_text="e.g., 'Kasarani, Near Naivas'", max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_open', models.BooleanField(default=True, help_text='Toggle this to show/hide on the map')),
                ('price_per_20l', models.DecimalField(decimal_places=2, default=50.0, help_text='Price for one 20L Jerrycan', max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed delivery fee (0 for free delivery)', max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of 20L Jerrycans', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('delivery_address', models.TextField(help_text='Detailed address or landmarks')),
                ('customer_phone', models.CharField(help_text='Phone number for this specific order', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DELIVERING', 'Out for Delivery'), ('COMPLETED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='waterapp.watervendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
