# Generated by Django 5.2.8 on 2025-12-19 19:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0006_watervendor_waterorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='watervendor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin must check this for vendor to appear on map'),
        ),
        migrations.AlterField(
            model_name='watervendor',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed delivery fee (0 for free delivery)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='watervendor',
            name='price_per_20l',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Price for one 20L Jerrycan', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
