# Generated by Django 5.2.8 on 2025-12-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0007_watervendor_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='waterapp.watervendor')),
            ],
        ),
    ]
