# Generated by Django 5.2.8 on 2025-12-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0010_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='watervendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
    ]
