# Generated by Django 5.2.8 on 2025-12-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0011_watervendor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='waterapp.watervendor'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='water_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='waterapp.watersource'),
        ),
    ]
